public class Address {
    public void homeAddress() {

        string name='Harun';
        integer numOfFamilyMembers= 3;
        string houseName='Evim';
        integer houseNumber= 7798;
        string streetName='Primrose';
        string cityName='Dallas';
        string stateName='Texas';
        string stateIsoCode='US-TX';
        string countryName='USA';
        string countryIsoCode='3266-2';
        integer zipCode=75082;
        boolean isCurrentHome=true;

        system.debug(name);
        system.debug(numOfFamilyMembers);
        system.debug(houseName);
        system.debug(houseNumber);
        system.debug(streetName);
        system.debug(cityName);
        system.debug(stateName);
        system.debug(stateIsoCode);
        system.debug(countryName);
        system.debug(countryIsoCode);
        system.debug(zipCode);
        system.debug(isCurrentHome);



    }
}
